apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-clair
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: quay/overlays/clair
    repoURL: https://github.com/kevchu3/ocp4-gitops-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
