apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false 
  name: multitenant-quotas-project-template
  namespace: openshift-config
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${PROJECT_ADMIN_USER}
# Must also apply multitenant AdminNetworkPolicy because this NetworkPolicy denies all selected pods outside of this namespace
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-same-namespace
  spec:
    podSelector: {}
    ingress:
    - from:
      - podSelector: {}
# Set resource quotas per project
# https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/building_applications/quotas#quotas-setting-per-project
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute
  spec:
    hard:
      requests.cpu: 4
      requests.memory: 24Gi
      limits.memory: 24Gi
# Set limit range so that pods fit within quota
# https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/nodes/working-with-clusters#nodes-cluster-limit-ranges
- apiVersion: v1
  kind: "LimitRange"
  metadata:
    name: "compute"
  spec:
    limits:
    - max:
        cpu: "4"
        memory: 8Gi
      min:
        cpu: 50m
        memory: 4Mi
      type: Pod
    - default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: 50m
        memory: 1Gi
      max:
        cpu: "4"
        memory: 8Gi
      maxLimitRequestRatio:
        cpu: "50"
      min:
        cpu: 50m
        memory: 4Mi
      type: Container
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
