apiVersion: batch/v1
kind: Job
metadata:
  name: add-cluster-monitoring-view-clusterrole
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: add-cluster-monitoring-view-clusterrole
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
            - /bin/bash
            - -c
            - |
              oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount
      restartPolicy: Never
      serviceAccountName: grafana-operator
  backoffLimit: 0
