apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy custom Grafana from OperatorHub based on this blog:
# https://www.redhat.com/en/blog/custom-grafana-dashboards-red-hat-openshift-container-platform-4

resources:
  - subscription.yaml
  - grafana.yaml
  - secret.yaml
  - rolebindings.yaml
  - patch-grafanadatasource.yaml
