apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: prometheus-grafanadatasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: my-grafana
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: "grafana-credentials"
          key: "token"
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: 'Authorization'
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    secureJsonData:
      httpHeaderValue1: 'Bearer ${token}'
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-grafanadatasource
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
      - name: patch-grafanadatasource
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
            - /bin/bash
            - -c
            - |
              set -e
              NEW_TOKEN=`oc create token grafana-sa --duration=876000h -n my-grafana`
              oc set data secret/grafana-credentials token=`echo ${NEW_TOKEN}`
              oc delete pod -l app=grafana
      restartPolicy: Never
      serviceAccountName: grafana-sa
      terminationGracePeriodSeconds: 60
