apiVersion: batch/v1
kind: Job
metadata:
  name: patch-grafanadatasource
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: patch-grafanadatasource
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
            - /bin/bash
            - -c
            - |
              set -e
              NEW_TOKEN=`oc serviceaccounts get-token grafana-serviceaccount -n my-grafana`
              oc patch grafanadatasource prometheus-grafanadatasource -n my-grafana --type='json' -p='[{"op":"add","path":"/spec/datasources/0/secureJsonData/httpHeaderValue1","value":"Bearer '${NEW_TOKEN}'"}]'
      restartPolicy: Never
      serviceAccountName: grafana-operator
      terminationGracePeriodSeconds: 60
