# https://grafana.github.io/grafana-operator/docs/examples/datasource_variables/readme/
# https://docs.openshift.com/container-platform/4.13/nodes/pods/nodes-pods-secrets.html#nodes-pods-secrets-creating-sa_nodes-pods-secrets
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    kubernetes.io/service-account.name: "grafana-sa"
type: kubernetes.io/service-account-token
