apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: my-grafana
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v3.10.1
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana
spec:
  targetNamespaces:
   - grafana
