apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: my-grafana
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v4.0.2
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana
spec:
  targetNamespaces:
   - my-grafana
